name: Setup Env
description: Setup Env for Linux x64
inputs:
  token:
    description: 'A Github PAT'
    required: true
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
    - name: Load dependencies
      shell: bash
      run: nix develop --install
    - uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: |
          ~/.cache/go-build
          /tmp/go/pkg/mod/
