// Package difftest is the differential-testing harness comparing this
// repo's interpreter against the vendored legacy ledger "machine" (see
// internal/oracle), on programs generated by internal/gen.
//
// It's its own Go module (see go.mod) — separate from both the root module
// and internal/oracle — wired together with local `replace` directives so
// it can import the public API of the root module AND the (deliberately
// un-importable-from-elsewhere) oracle, without either of THOSE modules
// ever depending on this one.
package difftest

import (
	"context"
	"math/rand"

	"github.com/formancehq/numscript/internal/gen"
)

// Case is one generated script plus both engines' results and the verdict.
type Case struct {
	Script  string
	Vars    map[string]string
	New     SideResult
	Oracle  SideResult
	Verdict Verdict
}

// RunOne generates one program from rng, runs it against both engines, and
// compares the results.
func RunOne(ctx context.Context, rng *rand.Rand) Case {
	vars, balances, script := gen.GenerateScript(rng)

	newRes := runNew(ctx, script, vars, balances)
	oracleRes := runOracle(ctx, script, vars, balances)

	return Case{
		Script:  script,
		Vars:    vars,
		New:     newRes,
		Oracle:  oracleRes,
		Verdict: Compare(newRes, oracleRes),
	}
}
