name: Default
on:
  merge_group:
  push:
    branches:
      - main
      - release/*
      - releases/*
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled, edited ]

permissions:
  contents: read

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  PR:
    if: github.event_name == 'pull_request'
    uses: formancehq/ci/.github/workflows/go-pr.yml@main
    permissions:
      pull-requests: read
      statuses: write

  Dirty:
    runs-on: namespace-profile-linux-amd64-4vcpu
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
        with:
          fetch-depth: 0
          dissociate: true

      - uses: formancehq/ci/actions/setup-nix@main

      - run: nix develop --impure --command just pre-commit

      - name: Get changed files
        shell: bash
        run: |
          hasChanged=$(git status --porcelain)
          if (( $(echo ${#hasChanged}) != 0 )); then
            git status
            echo "There are changes in the repository"
            git diff
            exit 1
          fi

  Tests:
    needs: [Dirty]
    runs-on: namespace-profile-linux-amd64-4vcpu
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
        with:
          fetch-depth: 0
          dissociate: true

      - uses: formancehq/ci/actions/setup-nix@main

      - run: nix develop --impure --command just tests

      - uses: codecov/codecov-action@v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  GoReleaser:
    needs: [Dirty]
    uses: formancehq/ci/.github/workflows/go-build.yml@main
    with:
      build-condition: main-and-label
      build-label: build-images
    secrets:
      NUMARY_GITHUB_TOKEN: ${{ secrets.NUMARY_GITHUB_TOKEN }}
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
